# Generated by Django 2.2.24 on 2022-12-05 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
