# Generated by Django 2.2.24 on 2022-12-05 01:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221205_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='CA', verbose_name='Нормализованный номер телефона'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='phonenumber',
            field=models.CharField(max_length=20, verbose_name='Номер владельца'),
        ),
    ]
