# Generated by Django 2.2.24 on 2022-12-05 01:40

from django.db import migrations

def fill_owner(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')
    for flat in flats.objects.all():
        owners.objects.get_or_create(owner=flat.owner, defaults={
            'owners_phonenumber': flat.owners_phonenumber,
            'owner_pure_phone': flat.owner_pure_phone,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221205_0339'),
    ]

    operations = [
        migrations.RunPython(fill_owner),
    ]
