# Generated by Django 2.2.24 on 2022-12-05 02:03

from django.db import migrations

def add_flats_owner(apps,  schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')
    flats_set = flats.objects.all()
    if flats_set.exists():
        for flat in flats_set.iterator():
            owner, created = owners.objects.get_or_create(owner=flat.owner)
            owner.flats.add(flat)
            owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20221205_0356'),
    ]

    operations = [
        migrations.RunPython(add_flats_owner)
    ]
